# Build the manager binary
FROM golang:1.17 as builder

WORKDIR /workspace
ENV GOPROXY https://goproxy.cn,direct
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY api/ api/
COPY pkg/ pkg/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o cita-node-cli pkg/main/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM debian:bullseye-slim
WORKDIR /
COPY --from=builder /workspace/cita-node-cli .
COPY --from=registry.devops.rivtower.com/cita-cloud/cloud-op:latest /usr/bin/cloud-op /usr/bin/
#USER 65532:65532

ENTRYPOINT ["/cita-node-cli"]
