# permissions for end users to view blockheightfallbacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockheightfallback-viewer-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - blockheightfallbacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - blockheightfallbacks/status
  verbs:
  - get
