# permissions for end users to edit changeowners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: changeowner-editor-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - changeowners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - changeowners/status
  verbs:
  - get
