# permissions for end users to view citanodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citanode-viewer-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - citanodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - citanodes/status
  verbs:
  - get
