# permissions for end users to edit duplicates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: duplicate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cita-node-operator
    app.kubernetes.io/part-of: cita-node-operator
    app.kubernetes.io/managed-by: kustomize
  name: duplicate-editor-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - duplicates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - duplicates/status
  verbs:
  - get
