# permissions for end users to view recovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recover-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cita-node-operator
    app.kubernetes.io/part-of: cita-node-operator
    app.kubernetes.io/managed-by: kustomize
  name: recover-viewer-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - recovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - recovers/status
  verbs:
  - get
