---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cita-node-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - blockheightfallbacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - blockheightfallbacks/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - blockheightfallbacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - changeowners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - changeowners/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - changeowners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - citanodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - citanodes/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - citanodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - duplicates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - duplicates/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - duplicates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - recovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - recovers/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - recovers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - snapshots/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
