# permissions for end users to edit switchovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchover-editor-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers/status
  verbs:
  - get
