# permissions for end users to view switchovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchover-viewer-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - switchovers/status
  verbs:
  - get
