apiVersion: citacloud.rivtower.com/v1
kind: Restore
metadata:
  name: restore-sample-cloud-config
  namespace: default
spec:
  chain: test-chain-zenoh-bft
  node: test-chain-zenoh-bft-node0
  deployMethod: cloud-config
  snapshot: snapshot-sample
  pullPolicy: Always
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:snapshot
  podAffinityFlag: true
