apiVersion: citacloud.rivtower.com/v1
kind: Snapshot
metadata:
  name: snapshot-sample
  namespace: default
spec:
  chain: test-chain-zenoh-bft
  node: test-chain-zenoh-bft-node0
  blockHeight: 50
  deployMethod: cloud-config
  action: Direct
  storageClass: nfs-client
  pullPolicy: Always
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:snapshot
  podAffinityFlag: true
  ttlSecondsAfterFinished: 300
