apiVersion: citacloud.rivtower.com/v1
kind: Switchover
metadata:
  name: switchover-sample-2
  namespace: default
spec:
  chain: test-chain-zenoh-bft
  sourceNode: test-chain-zenoh-bft-node1
  destNode: test-chain-zenoh-bft-node0
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:switchover
  pullPolicy: Always
  ttlSecondsAfterFinished: 300
