apiVersion: citacloud.rivtower.com/v1
kind: Backup
metadata:
  name: backup-sample-cloud-config
  namespace: cita
spec:
  chain: test-chain-zenoh-bft
  namespace: cita
  node: test-chain-zenoh-bft-node0
  deployMethod: cloud-config
  storageClass: nas-client-provisioner
  pullPolicy: Always