apiVersion: citacloud.rivtower.com/v1
kind: Switchover
metadata:
  name: switchover-sample
  namespace: cita
spec:
  chain: test-chain-zenoh-bft
  sourceNode: test-chain-zenoh-bft-node0
  destNode: test-chain-zenoh-bft-node1
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:switchover
  pullPolicy: Always
