apiVersion: citacloud.rivtower.com/v1
kind: Duplicate
metadata:
  name: duplicate-sample
  namespace: zhujq
spec:
  chain: test-chain-zenoh-overlord
  node: test-chain-zenoh-overlord-node0
  deployMethod: cloud-config
  backend:
    pvc: local-pvc
    path: /data/my-chain-0
  action: StopAndStart
  pullPolicy: Always
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:compress
  podAffinityFlag: true
  ttlSecondsAfterFinished: 300
#  compress:
#    type: gzip
#    file: cita.tar.gz


