apiVersion: citacloud.rivtower.com/v1
kind: Backup
metadata:
  name: backup-sample-cloud-config
  namespace: zhujq
spec:
  chain: test-chain-zenoh-overlord
  node: test-chain-zenoh-overlord-node0
  deployMethod: cloud-config
#  pvcSize: 5Gi
  storageClass: nfs-client
  pullPolicy: Always
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:wjj
  podAffinityFlag: true
  ttlSecondsAfterFinished: 300