apiVersion: citacloud.rivtower.com/v1
kind: BlockHeightFallback
metadata:
  name: blockheightfallback-sample
  namespace: app-rivspace
spec:
  chain: chain-734116911817822208
  node: chain-734116911817822208-0
  blockHeight: 2000000
  deployMethod: python
  pullPolicy: Always
