apiVersion: citacloud.rivtower.com/v1
kind: Switchover
metadata:
  name: switchover-sample
  namespace: default
spec:
  chain: test-chain-zenoh-overlord
  sourceNode: test-chain-zenoh-overlord-node0
  destNode: test-chain-zenoh-overlord-node1
  image: registry.devops.rivtower.com/cita-cloud/cita-node-job:switchover
  pullPolicy: Always
  ttlSecondsAfterFinished: 300
