name: Build Latest Docker Images

on:
  push:
    branches:
      - master
      - main
#  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-latest:
    name: "Build latest image"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: "Login to DockerHub"
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: "Building docker images"
      env:
        IMG_REGISTRY: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      run: |
        set -e
        make image-latest
        make job-image-latest