name: Run Test && Build Latest Docker Images

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  testing:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v2
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: "Env Tests"
        run: |
          make test
  build-latest:
    name: "Build latest image"
    needs: testing
    runs-on: [self-hosted, Linux, alibaba-cloud]
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:master
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Building docker images"
        run: |
          make image-latest